# go-installation-playbook.yml
---
- name: Install Go version
  hosts: all
  vars:
     - version: {{ morpheus['customOptions']['goVersion'] }}
  tasks:
    - name: Download go tar file
      command: wget https://go.dev/dl/go{{version}}.linux-amd64.tar.gz

    - name: Delete previous installation
      command: rm -rf /usr/local/go
      become: true

    - name: Extract and move new go folder to /usr/local
      command: tar -C /usr/local -xzf go{{version}}.linux-amd64.tar.gz
      become: true

    - name: Delete downloaded tar file
      shell: rm -rf go{{version}}.linux-amd64.tar.gz*

    - name: Add go binary path to ~/.profile
      lineinfile:
        path: ~/.profile
        line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
        create: true
        state: present

    - name: Source updated profile and test go version
      shell: . ~/.profile && go version
